version: "3.8"

services:
  mongo:
    image: mongo:5.0.5
    ports:
      - 37017:27017
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
#  redis:
#    image: redis:6.0-alpine
#    container_name: camel_redis
#    ports:
#      - 7379:6379
#    volumes:
#      - redis_data:/data
#    healthcheck:
#      test: redis-cli ping
#      interval: 1s
#      timeout: 3s
#      retries: 30
#    deploy:
#      resources:
#        limits:
#          cpus: "0.2"
#          memory: 300M

volumes:
  mongo_data: { }
#  redis_data: { }
